name: Release Production

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: master

      - name: Update package.json version
        run: |
          jq '.version = "${{ steps.semver.outputs.next }}"' package.json > temp.json && mv temp.json package.json
          cat package.json

      - name: Push tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "release: ${{ steps.semver.outputs.next }}"
          git tag ${{ steps.semver.outputs.next }}
          git push origin master --tags

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ steps.semver.outputs.next }}
          allowUpdates: true
          draft: false
          makeLatest: true
          generateReleaseNotes: true
          name: ${{ steps.semver.outputs.next }}
          body: Changelog Contents
          token: ${{ github.token }}
